features:
  no-default-permissions: true
  launch-control:
    enabled: false
    launch-at:
      year: 2021
      month: 9
      day: 14
      hour: 20
      minute: 00
  unload-spawn-chunks: true
  auto-restart:
    enabled: false
    restart-after: 21600
    idle-time: 300
  sit: true
  custom-portals: false
  chat: true